blackducksoftware/ohloh-ui

lib/tasks/failure_group.rake

This script would run via cron every one hour (like in old ohloh source) and this would be deployed to the production utility server
```ruby
RAILS_ENV=production bundle exec rake jobs:reschedule_failure_group
```

OTWO-4837 AutoReschedule a FailureGroup should have the jobs re-run

---

app/core_extensions/ruby/string.rb
app/models/widget/project_widget/partner_badge.rb
app/models/widget/project_widget/thin_badge.rb

the imagemagick breaks only when single quote is encountered. So when a string has "fon'tli" ..it breaks.
```ruby
MiniMagick::Error (`convert -size 150x26 xc:white -font /home/vagrant/projects/ohloh-ui/app/assets/fonts/OpenSans-Regular.ttf -fill rgb( 0%, 0%, 0% ) -stroke #0099ff -pointsize 14 -weight 350 -gravity North -draw text 0,3 'fo n'tli' /tmp/image-base-20170727-10609-b156cp.png` failed with error:
```
So now the shellword is removed and we're escaping single quote so that the forward slash(\) won't appear in the Badges.

OTWO-4864 Fixed the forward slash on Badges

---

app/controllers/unclaimed_controller.rb
test/controllers/committers_controller_test.rb
test/support/unclaimed_controller_test.rb

This fixes the case where a high number of people objects cause memory hog in the default index results.

OTWO-4856 Fix committers#index memory hog

---

app/controllers/edits_controller.rb
app/models/edit.rb
app/models/project.rb
script/delete_google_code_projects.rb

Also made a change to allow for project.undo will also perform enlistment.undo.  Refactored code that was in controller and put it into the Edit model.

OTWO-4928  - Script to delete obsolete GoogleCode projects

---

app/models/enlistment.rb
test/controllers/enlistments_controller_test.rb
test/models/enlistment_test.rb

Sorting by *Update Status* should first sort by status and then sort by last updated job.
Also fixed the intermittently failing test.

OTWO-4963 Fix enlistments sort by Update Status

---

Gemfile
Gemfile.lock
config/initializers/slowpoke_setup.rb

Timeout prevents memory bloat from occuring. We need to investigate the memory bloat in order to fix it.

Remove timeout plugin to debug memory hog

---

app/models/concerns/code_location_jobs.rb
app/models/project_license.rb
test/factories/jobs.rb
test/models/code_location_test.rb

The Code Location "schedule_fetch" would return if there were any
incomplete jobs, ostensibly because those jobs need to be completed
first.
However, the existence of a TarballJob causes problems with this. The
Project and Code Locations are not dependent upon a TarballJob
successfully completing. However, if there was a failed TarballJob, the
"incomplete" state is true, and no new job would be created.
The fix in this change set is to filter out TarballJobs from the set of
incomplete or new jobs (those that finished within the last 5 minutes).
Frankly, the author has some concerns about this blanket 5 minute
policy, but isn't attempting to address it now.
The test code illustrates that the TarballJob must belong to the Code
Location and have the Code Locations's best code set recoreded …

Ignore TarballJobs when scheduling a fetch

---

app/controllers/application_controller.rb
app/controllers/concerns/clearance_setup.rb
test/lib/clearance_test.rb

With the migration to Clearance, we lost the ability to login with an
email address.  This restores that feature.
There was also a regression failure where a disabled account was being
redirected to the "authenticate new" path. This was due to the
"!current_user.access.disabled?" in the
ApplicationController#redirect_for_spammer_verification method.  When a
user is disabled, then they'll get caught by a later before_action
filter, so this check isn't needed here.

OTWO-5039 Restore login with email

---

config/locales/accounts.en.yml
config/locales/deleted_accounts.en.yml
config/locales/organizations.en.yml

Fixed the issue on OSX when running rake or ay other commands
`I18n::InvalidLocaleData: can not load translations from config/locales/accounts.en.yml: #<Psych::SyntaxError: (accounts.en.yml): found unknown escape character while parsing a quoted scalar`

Fixed i18n compatible issue

---

app/assets/javascripts/github_auth.js.coffee
app/controllers/authentications_controller.rb
app/models/account/login_formatter.rb
app/models/github_api.rb
test/controllers/authentications_controller_test.rb
test/models/account/login_formatter_test.rb

- This PR will also add functionality to check for an account matching with Github secondary email addresses.
- Also avoid multiple click on Sign in with Github.

OTWO-5418 Fixed the github login to do case insensitive search by account login

---

db/migrate/20190529010101_alter_slave_and_jobs_table.rb

This PR removes an inadvertent migration meant for the fisbot database (and not ohloh-ui).  It's presence in ohloh-ui hinders running the server; ie after a db refresh/reload, the server expects the migration to be present and generates a respective migration error until this issue is resolved manually in the ohloh-ui database.  Thanks  to @msk999 for helping to identify and resolve this issue.

this migration shouldn't be in ohloh-ui

---

app/controllers/concerns/vulnerability_filters.rb
app/helpers/vulnerabilities_helper.rb
app/views/vulnerabilities/_version_filter.html.haml
test/helpers/vulnerabilities_helper_test.rb

This PR addresses an issue where the dropdown listing for Vulnerabilities on the `projects#security` page is sorted by respective release date and should be correctly sorted using semantic versioning.  Using a sort by semantic versioning will correctly group all releases listed and not jumble the listing based on the most recent releases; the `projects#security` UI still presents a vulnerability timeline which lists the respective releases for the selected time span.
Refer to https://semver.org for a description on semantic versioning.
This PR converts each respective version string to an array of int for each element in the version string; non-numeric chars, '+', '-', and '_' are translated to their equivalent ASCII values and multiplied by -1 with respect to sorting.  The sorting is …

OTWO 5804 - sort vulnerabilities dropdown by version number

---

app/helpers/vulnerabilities_helper.rb
test/helpers/vulnerabilities_helper_test.rb

This PR fixes errors that block a user from accessing projects#security.
The error occurs when sorting the version names that comprise the dropdown in the Vulnerabilities section of the Projects Security page, and is related to non-standard semantic version patterns used within a number of projects hosted on OpenHub. 
The first fix recognizes non-standard chars in version names, such that `nil` is no longer assigned for non-standard chars in the array to be sorted, which was causing `comparison of Array with Array failed`
The second fix checks for a `nil` token passed to `get_token_array` and simply returns an empty array (`[]`).  Release names that ended with a hyphen (ie: `TestRelease-.x.y.z`) were found to cause this issue.
Tests have been augmented such that release names which were …

OTWO-5831: Fix invalid version patterns breaking project#security

---

app/assets/stylesheets/account.sass
app/assets/stylesheets/accounts/show.sass
app/assets/stylesheets/bootstrap.sass
app/assets/stylesheets/buttons.sass
app/assets/stylesheets/charts.sass
app/assets/stylesheets/chosen-overrides.sass
app/assets/stylesheets/committers.sass
app/assets/stylesheets/dynamic.sass
app/assets/stylesheets/explore.sass
app/assets/stylesheets/footer.sass
app/assets/stylesheets/forums_topics_posts.sass
app/assets/stylesheets/home.sass
app/assets/stylesheets/menu_bar.sass
app/assets/stylesheets/oh-styles.sass
app/assets/stylesheets/organizations.sass
app/assets/stylesheets/page.sass
app/assets/stylesheets/projects.sass
app/assets/stylesheets/search-dingus.sass
app/assets/stylesheets/sidebar.sass
app/assets/stylesheets/static_forms.sass
app/assets/stylesheets/tags.sass
app/decorators/vulnerability/all_version_chart.rb
app/decorators/vulnerability/version_chart.rb
app/views/edits/_edit.html.haml
config/charting/project_vulnerability_version.yml

This PR addresses the OTWO color updates to 'explore#people',
and other minor updates regarding the mockup on OTWO-5758.
This PR also addresses the background margin colors on the home 
and projects pages, vulnerability chart hover colors/issues, using
text & css to replace the old colored 'OH' avatar, and other minor
updates.

OTWO-5760: Update the Explore People page using the Mockup

---

app/assets/stylesheets/dynamic.sass
app/assets/stylesheets/oh-colors.sass
app/assets/stylesheets/organizations.sass
app/assets/stylesheets/orgs.sass
app/assets/stylesheets/page.sass

This PR updates the explore#organization page regarding the 2019 OH Style Guide (and mock-ups in OTWO-5758).
This PR also addresses 1) highlighting the 'Tools' selection in the menu bar and 2) full-width layout for projects#show and related pages (projects#security, etc...) as described in the bullet points of OTWO-5924.

OTWO 5761 - Update the Explore Organization page

---

app/assets/stylesheets/base.sass
app/assets/stylesheets/charts.sass
app/assets/stylesheets/oh-styles.sass
app/assets/stylesheets/projects.sass
app/assets/stylesheets/search-dingus.sass
app/assets/stylesheets/static_forms.sass
app/views/layouts/partials/_footer.html.haml
app/views/projects/show/_security.html.haml
config/charting/analysis/options_based_on_type.yml
config/charting/project_vulnerability_version.yml

This PR addresses a number of issues accumulated as the Ohloh UI Trade Dress has been updated.  A number of these issues deal with Highcharts discrepancies after updating the Highcharts API to 8.0.  
Also, directly importing the `highcharts.css` file lead to a number of adverse issues with charts with `styledMode = true`.  Instead, the necessary Highcharts styling classes should be added and extended as necessary.  Refer to OTWO-5767, which also resolves some Highchart issues in this regard.

OTWO-5924: Ohloh UI Update Punchlist 2020-01-23

---

app/assets/stylesheets/accounts/show.sass
app/assets/stylesheets/charts.sass
app/assets/stylesheets/oh-colors.sass
app/assets/stylesheets/oh-styles.sass
app/assets/stylesheets/search-dingus.sass
app/assets/stylesheets/streamgraph.sass
app/views/accounts/show/_header.html.haml
app/views/shared/_search.html.haml
config/charting/defaults.yml

This PR addresses the updates re the new Ohloh UI Trade Dress to the `accounts#show` page referenced in the [2019 OH Style Guide ](https://sig-confluence.internal.synopsys.com/pages/viewpage.action?spaceKey=O2&title=2019+OH+Style+Guide)
This PR highlights the color updates to the `commits_by_project` chart, as well as addressing some global color updates to such elements as the timestamp signature, search box controls, and footer navigation colors.  These are also referenced in the 2019 OH Style Guide.

OTWO-5930: Update CSS for Account Show page

---

app/assets/stylesheets/base.sass
app/assets/stylesheets/charts.sass
app/assets/stylesheets/fontawesome_icons.sass
app/assets/stylesheets/oh-colors.sass
app/assets/stylesheets/oh-styles.sass
app/assets/stylesheets/project_summary.sass
app/views/shared/search_dingus/_commits_or_contributor_search.html.haml

This PR addresses updating the colors defined for the `commits#index` and `commits#summary` pages, with respect to the new UI Trade Dress. 
A few issues are still open before squashing and merging to the feature branch:
1) color updates for the range buttons on the Commits Per Month chart
2) color definition for the Commits Per Month chart
3) should the "Month Recent Commits" heading be revised to "Most Recent Commits"?

OTWO-5765: Update CSS for the Project Commits pages

---

app/assets/stylesheets/ace-fixes.sass
app/assets/stylesheets/base.sass

This PR addresses issues that were found after verifying all the items described in OTWO-5939; specifically, updating the button color ('Choose'/'Change') for the ACE file upload.  This PR also updates the use of Roboto fonts for FontAwesome icons used in the Account header (`mini_account_row`).

OTWO-5939: UPDATE, Punchlist 2020-02-06

---

config/locales/factoids.en.yml

Two of the team size strings began with "by", leading to
"maintained by by one developer".

Remove duplicate word "by" in team size strings.

---

Gemfile
Gemfile.lock

* rake assets:precompile loads the initializers.
* Initializers require app/lib which connects to the DB.
* We want to compile assets in base Docker image.
* Use DATABASE_URL=nulldb://user:pass@127.0.0.1/dbname
* Downgraded bundler version to accurately reflect rails 4 deps.

OTWO-6438 NullDB to for asset compilation w/o DB

---

Gemfile
Gemfile.lock

binding_of_caller -> Binding.of_caller is not used anywhere.
guard -> If one needs guard, they can install it individually.
meta_request -> Used for a chrome extension
flog -> Install this locally if needed. We do not need it in Gemfile.
m -> Rails 5 already provides a way to run tests by line number.
ruby_parser -> we do not use this anywhere.
spring -> raises exceptions related to autoload on running tests.
capybara, selenium, jasmine & spinach -> No integration tests right now.
pry -> Install this locally if needed. We do not need it in Gemfile.
rails-erd -> Install this locally when needed.
rb-readline -> This is not used anywhere.
rubocop-faker -> We do not call rubocop with this extension.

Cleanup unused test & development gems

---

app/controllers/oh_admin/license_permissions_controller.rb
app/controllers/privacy_controller.rb
app/helpers/dashboard_helper.rb
app/models/position/hooks.rb

In Rails 4 `uniq` was an alias for `distinct`. This was removed in Rails 5. 
The code didn't break because Enumerable has a `uniq` method. So the
current logic was defaulting to Array's `uniq`.
This caused performance issues on the admin page.

OTWO-6567 Replace uniq with sql distinct

---

app/views/enlistments/index.html.haml
app/views/forums/_notice.html.haml

Use the forum link instead of registration page.
It is hard for end users to find the forum otherwise.
Registration page is relatively easy to find.

OTWO-6817 Fix community forum registration link
